### ISSUE TITLE
Users don't know which squares can be captured

### ISSUE THREAD

**Issue by cbrwizard** [cbrwizard/picswars.io#106]
Need to change the way capturable squares are shown. Perhaps they should have an emoji icon on top of them?

**Comment by cbrwizard** [comment]
Let's try adding a semi-transparent capture emoji flag on squares which can be capturable instead of changing borders. When hovered - the flag should stop being transparent.

**Comment by fyodoriv** [comment]
Ok this is quite hard, so let's postpone it. Hopefully the tutorial should help

**Comment by fyodoriv** [comment]
Added the basic info to the tutorial; hopefully it will help
