### ISSUE TITLE
Allow placing images on top of captured territories

### ISSUE THREAD

**Issue by cbrwizard** [cbrwizard/picswars.io#108]
Need to properly investigate whether it is needed for a project, because that's a lot of work here.

A current theory is that it's needed for the companies to properly get interested in this game as a platform.

- [x] Allow uploading images
- [x] Place an image on top of the whole player's territory

**Comment by cbrwizard** [comment]
If audience shows their interest in this https://github.com/cbrwizard/squardak/issues/117, I need to implement it quickly and unpolished to quickly test my idea. That means, to execute it in a single next sprint and after that ask players again.

**Comment by cbrwizard** [comment]
An idea: that image should basically act like a sprite for each square object.

First of all, to determine the image size, a rectangular is drawn over the whole user's territory so that every square is inside of it. That rectangular basically has the same size the image should have.
Next, an image is resized(or its resize ratio is stored) and every square now uses that image as a sprite in its background, taking the width, height, x and y.

When we upload the image, we should create and store 3 copies: small, medium and big sizes and download the needed ones.

When the player is in the login screen, the images should start downloading already.

**Comment by fyodoriv** [comment]
All right, looks like Google's Cloud Vision API is the only service I've found with both nudity and violence filters, so let's invest into that. https://cloud.google.com/blog/big-data/2016/08/filtering-inappropriate-content-with-the-cloud-vision-api

**Comment by fyodoriv** [comment]
On the other hand, let's work on censorship later, when it's needed.

**Comment by fyodoriv** [comment]
Done!
