### ISSUE TITLE
Name is too complicated 

### ISSUE THREAD

**Issue by cbrwizard** [cbrwizard/picswars.io#123]
Squardak makes no sense for anyone but me and it's hard to write and remember correctly.

Instead of that, a game should have a name which immediately helps a person understand what is this going to be about.

Thus, let's rename the game as Pics Wars. That way, people know: that it's something fun; it's about wars (it's action or strategy); it has pictures.

The existing domains should redirect to a new one.

- [x] Buy an io domain
- [x] Change titles, all code texts
- [x] Create a new logo (same style, different letters for now), description (Capture territories. Post pictures. Dominate the field!)
- [x] Update the name in ALL INTERNETS
- [x] Make picswars.io the main domain, let all others redirect there
- [x] Test manually

**Comment by cbrwizard** [comment]
Woah, looks like investing in a .io domain is worth it. People actually call them 'io games' and categorize them by that. http://iogames.space/category/io-games It's something like an indicator that this game is modern.

**Comment by fyodoriv** [comment]
Done! It might be worth buying the domain pixwars.io and adding a redirect, but let's see.
