### ISSUE TITLE
First come users don't understand what to do and how to get fun

### ISSUE THREAD

**Issue by cbrwizard** [cbrwizard/picswars.io#35]
Especially it might be confusing when there aren't many squares around.

**Comment by cbrwizard** [comment]
https://github.com/cbrwizard/squardak/issues/86

**Comment by cbrwizard** [comment]
Possible solutions: https://github.com/cbrwizard/squardak/issues/94, https://github.com/cbrwizard/squardak/issues/69

**Comment by cbrwizard** [comment]
Hopefully done. If the metric results aren't satisfactory, it might be needed to add a popup on the game start with short game rules and screenshots (this popup should also be activatable on a Help icon click).

**Comment by cbrwizard** [comment]
The results are still bad! Let's add a tutorial. We should come up with an idea for it. It can be a popup dialog on the start or a neat interactive one.

**Comment by cbrwizard** [comment]
Also fix https://github.com/cbrwizard/squardak/issues/105 with the tutorial

**Comment by cbrwizard** [comment]
An interesting thing: people noted that they have no goal in this game.
There is indeed none at the moment.
If I add images there might be more fun, but still no goal.
I think that the goal will appear when the players can have a shared image together so that they act together like a community.

**Comment by cbrwizard** [comment]
That popup tutorial should have content something like this:


In this game, you will choose an image to represent you and capture territories so that everyone can see your picture. You can collaborate with other players so that your shared image dominates the field!

This is your square.
[An image of a square]

You can capture squares around them by clicking on a square and pressing the Capture button.
[A gif which does that]

The more squares you own, the more you can capture at the same time.
[A gif which captures multiple at once, with unselecting]

You can add an image to your territory to represent you by clicking on an image icon and uploading an image from the internet or from your device. (WIP)
[A gif which clicks on an icon and uploads an image from the url]

Or you can type your friend's or community's nickname to automatically copy their image. That way you can act as a team!
[A gif where they type in another player's nick and then the image gets copied and people see two close to each other players with the same image].

Have fun!

**Comment by fyodoriv** [comment]
Added a basic tutorial, let's see how it helps.
