### ISSUE TITLE
Rewrite hovering

### ISSUE THREAD

**Issue by cbrwizard** [cbrwizard/picswars.io#95]
Instead, add user nicks' labels on top of their territories. Also add shiny borders to their territories as a whole.

**Comment by cbrwizard** [comment]
Theory on how to approach labels: might need to create a group for every player with squares; add a label on the centers of these groups. 

Next, need to somehow add the borders. A theory here is that we should iterate every square and ask how bordered it should be and draw borders depending on that. That might require a lot of calculations...

**Comment by cbrwizard** [comment]
A much simpler approach: remove the hover info; on hover dispatch the same action; when some data is in state: display it in a div which always follows the cursor and which is visible only when it has data.

**Comment by cbrwizard** [comment]
Try dispatching hover/unhover events only when data is different

**Comment by fyodoriv** [comment]
Done. Could be done better, but but
